#!/bin/sh

exe=$(
  which -a "$(basename "$0")" | (
    while IFS= read -r s; do
      if [ ! "$s" -ef "$0" ] && [ -x "$s" ]; then
        printf %s "$s"
        exit
      fi
    done
    exit 1
  )
) || exit 1

(
  sleep 0.1
  rm -f ~/.sudo_as_admin_successful
  sleep 0.4
  rm -f ~/.sudo_as_admin_successful
) &

exec "$exe" "$@"
