#!/bin/bash

target() {
  local p
  which -a "$(basename "$0")" | while IFS= read -r p; do
    if [ ! "$p" -ef "$0" ] && [ -x "$p" ]; then
      echo "$p"
      return 0
    fi
  done
  return 1
}

(
  for i in 1 4; do
    sleep 0.$i
    rm -f "$HOME/.sudo_as_admin_successful"
  done
)&

exec "$(target)" "$@"
