#!/bin/bash

exe=$(
  which -a "${0##*/}" | (
    while IFS= read -r s; do
      if [ ! "$s" -ef "$0" ] && [ -x "$s" ]; then
        printf %s "$s"
        exit
      fi
    done
    exit 1
  )
) || exit 1

exec "$exe" --no-hsts "$@"
