#!/bin/sh

compiler='/c/Program Files/AutoHotkey/Compiler'
bin=unicode.in
if [ -f "$bin" ]; then
  echo "'$bin' exists"
  exit 1
fi
cp "$compiler/Unicode 64-bit.bin" "$bin"
for src do
  MSYS2_ARG_CONV_EXCL=* "$compiler/Ahk2Exe.exe" /in "$src" /bin "$bin"
done
rm "$bin"
