#!/bin/bash

if [[ $IS_WSL || $WSL_DISTRO_NAME ]]; then
  >&2 echo 'WARNING: The script is running inside WSL.'
  >&2 echo 'You will want to shutdown WSL before running this script.'
  exit 1
fi

if [ "$#" = 0 ]; then
  >&2 echo "Usage: $(basename "$0") distro..."
  >&2 echo 'You will want to shutdown WSL before running this script.'
  exit 1
fi

compact() {
  diskpart << :
    select vdisk file=$1
    attach vdisk readonly
    compact vdisk
    detach vdisk
    exit
:
}

package_name() {
  echo CanonicalGroupLimited."$1"onWindows_79rhkp1fndgsc
}

disk_path() {
  echo "$(winenv localappdata)\\Packages\\$(package_name "$1")\\LocalState\\ext4.vhdx"
}

for dist; do
  compact "$(disk_path "$dist")"
done
