#!/usr/bin/env python3

import sys
import os
import argparse
from PIL import Image


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('im1', type=str, metavar='IMAGE1')
    parser.add_argument('im2', type=str, metavar='IMAGE2')
    parser.add_argument('-v', '--verbose', action='store_true')
    parser.add_argument('-a', '--all', action='store_true')
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()
    path1 = args.im1
    path2 = args.im2

    im1 = Image.open(path1)
    im2 = Image.open(path2)

    if im1.size != im2.size:
        print('Not the same size')
        sys.exit(1)

    if args.verbose:
        print(f'image-1: {im1.mode}')
        print(f'image-2: {im2.mode}')

    if im1.mode != im2.mode:
        im1 = im1.convert('RGBA')
        im2 = im2.convert('RGBA')

    el1 = im1.load()
    el2 = im2.load()

    rv = 0
    for i in range(im1.height):
        for j in range(im1.width):
            if el1[j, i] != el2[j, i]:
                rv = 1
                print(f'{path1} {path2} differ: row {i + 1}, column {j + 1}')
                if args.verbose:
                    print(f'  image-1 at ({i + 1}, {j + 1}): {el1[j, i]}')
                    print(f'  image-2 at ({i + 1}, {j + 1}): {el2[j, i]}')
                if not args.all:
                    sys.exit(rv)
    sys.exit(rv)
