#!/usr/bin/env ruby

require 'zlib'

unless dir = ARGV[0]
  puts <<~HELP
    Usage: #{File.basename($0)} DIRECTORY
    Rename each file in DIRECTORY to its CRC32, keeping file extension.
    HELP
  exit
end

Dir.glob File.join(dir, '*') do |p|
  if File.directory?(p) || File.realpath(p) == File.realpath($0)
    next
  end

  crc = Zlib.crc32(File.read(p))
  ext = File.extname(p)
  np = File.join(dir, '%08X%s' % [crc, ext])

  unless File.exist?(np)
    File.rename(p, np)
  end
end
