#!/usr/bin/env ruby

require 'base64'
require 'optparse'

opts = {}
OptionParser.new do |op|
  op.on('-d'){ opts[:decode] = true }
  op.parse!
end

mode = :encode
OptionParser.new do |op|
  op.on('-d'){ mode = :decode }
  op.parse!
end

case mode
when :encode
  puts Base64.urlsafe_encode64($<.read, padding: false)
when :decode
  print Base64.urlsafe_decode64($<.read.chomp)
end
