#!/bin/sh

# The name "clah" stands for "clear all history"

rm -f ~/.lesshst

rm -f ~/.ipython/profile_default/history.sqlite
rm -f ~/.irb?history
rm -f ~/.node_repl_history
rm -f ~/.python_history
rm -f ~/.rdbg_history

rm -f ~/.psql_history
rm -f ~/.rediscli_history
rm -f ~/.sqlite_history
