#!/usr/bin/env ruby

require 'erb'
require 'optparse'

mode = :encode
all = false
OptionParser.new do |op|
  op.on('-d') { mode = :decode }
  op.on('-a') { all = true }
  op.parse!
end

handler = case mode
when :encode
  if all
    -> s { s.unpack1('H*').upcase.gsub(/../, '%\&') }
  else
    -> s { ERB::Util.url_encode(s) }
  end
when :decode
  -> s { CGI.unescape(s) }
end

data = ARGV.size != 0 ? ARGV : ARGF.readlines(chomp: true)
puts data.map(&handler)
