#!/usr/bin/env ruby

require 'base64'
require 'optparse'

mode = :encode
linewise = false
OptionParser.new do |op|
  op.on('-d') { mode = :decode }
  op.on('-l') { linewise = true }
  op.parse!
end

case mode
when :encode
  puts Base64.urlsafe_encode64($<.read, padding: false)
when :decode
  if linewise
    $<.each(chomp: true) do |line|
      print Base64.urlsafe_decode64(line)
    end
  else
    print Base64.urlsafe_decode64($<.read.chomp)
  end
end
